# Generated by Django 3.1.8 on 2021-11-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditCardFD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload1',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
